### ISSUE TITLE
How can i view app on mobile device

### ISSUE THREAD

**Issue by lukephills** [estkin/boilerplate#4]
On the same network, navigating to MY-IP-ADDRESS:3000 doesn't work.

How can i view on a mobile device?

Thanks

**Comment by estkin** [comment]
So, u have running devServer on your machine and want to view it on mobile?

**Comment by lukephills** [comment]
Yeah thats right. Is it possible?

**Comment by estkin** [comment]
I don't think so. You will probably need to host in as production and then view it on that hosted url
